# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171124_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleup',
            name='updown',
            field=models.CharField(default=2, max_length=16, verbose_name='反对还是支持'),
            preserve_default=False,
        ),
    ]
