# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articleup_updown'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentup',
            name='updown',
            field=models.CharField(default=0, max_length=16, verbose_name='反对还是支持'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='commentup',
            unique_together=set([('comment', 'user')]),
        ),
    ]
